// Generated by npm run build:icons — do not edit by hand.
// The single, canonical list of every icon in the sprite.

export const iconNames = [
  "bell",
  "calendar",
  "check-circle",
  "download",
  "globe",
  "heart",
  "layout-dashboard",
  "lock",
  "search",
  "settings",
  "star",
  "users",
] as const;

export type IconName = (typeof iconNames)[number];
