// Generated by npm run build:icons — do not edit by hand.
// The single, canonical list of every icon in the sprite.

export const iconNames = [
  "bell",
  "calendar",
  "check-circle",
  "download",
  "file-text",
  "globe",
  "heart",
  "layout-dashboard",
  "lock",
  "log-out",
  "moon",
  "pencil",
  "search",
  "settings",
  "star",
  "sun",
  "upload",
  "users",
  "zap",
] as const;

export type IconName = (typeof iconNames)[number];
