/**
 * build-icons.mjs — turns the icon list into a single typed sprite.
 *
 * Input:
 *   src/icon/icon-list.ts  — the ids to pull from the `lucide-static` package.
 *
 * Outputs:
 *   public/icons/sprite.svg   — <symbol> per icon, served & cached once.
 *   src/icon/icon-names.ts    — `iconNames` (array) + `IconName` (type).
 *
 * No build-time dependencies beyond `lucide-static`: pure Node. icon-list.ts is
 * parsed as TEXT (regex), so it never has to be compiled or executed.
 *
 * Run with: npm run build:icons
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const listSourcePath = path.join(root, "src/icon/icon-list.ts");
const spriteOutPath = path.join(root, "public/icons/sprite.svg");
const typesOutPath = path.join(root, "src/icon/icon-names.ts");

/** Strip the outer <svg ...> wrapper, returning just the inner markup. */
export function innerOfSvg(svg) {
  return svg
    .replace(/^[\s\S]*?<svg[^>]*>/i, "")
    .replace(/<\/svg>[\s\S]*$/i, "")
    .trim();
}

/** Read the `lucideIcons` string array out of icon-list.ts (as text). */
async function readIconIds() {
  const text = await readFile(listSourcePath, "utf8");
  const block = text.match(/export const lucideIcons\s*=\s*\[([\s\S]*?)\]/);
  if (!block) return [];
  return [...block[1].matchAll(/["']([^"']+)["']/g)].map((m) => m[1]);
}

/** Read each id's SVG from the `lucide-static` package, then sort for stable diffs. */
async function readIcons() {
  const ids = await readIconIds();
  if (ids.length === 0) return [];

  const require = createRequire(import.meta.url);
  const iconsDir = path.join(path.dirname(require.resolve("lucide-static/package.json")), "icons");

  const icons = [];
  for (const id of ids) {
    try {
      const svg = await readFile(path.join(iconsDir, `${id}.svg`), "utf8");
      icons.push({ id, inner: innerOfSvg(svg) });
    } catch {
      console.warn(`⚠  lucide icon "${id}" not found in lucide-static — skipping.`);
    }
  }
  return icons.sort((a, b) => a.id.localeCompare(b.id));
}

function renderSprite(icons) {
  const symbols = icons.map(({ id, inner }) =>
    [
      `  <symbol id="${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">`,
      `    ${inner.replace(/\n\s*/g, "\n    ")}`,
      "  </symbol>",
    ].join("\n"),
  );

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Generated by npm run build:icons — do not edit by hand. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="display:none">`,
    "  <defs>",
    ...symbols,
    "  </defs>",
    "</svg>",
    "",
  ].join("\n");
}

function renderTypes(icons) {
  const all = icons.map(({ id }) => `  "${id}",`).join("\n");
  return [
    "// Generated by npm run build:icons — do not edit by hand.",
    "// The single, canonical list of every icon in the sprite.",
    "",
    "export const iconNames = [",
    all,
    "] as const;",
    "",
    "export type IconName = (typeof iconNames)[number];",
    "",
  ].join("\n");
}

async function main() {
  const icons = await readIcons();

  if (icons.length === 0) {
    console.error("No icons found — check src/icon/icon-list.ts and that lucide-static is installed.");
    process.exit(1);
  }

  await mkdir(path.dirname(spriteOutPath), { recursive: true });
  await Promise.all([
    writeFile(spriteOutPath, renderSprite(icons), "utf8"),
    writeFile(typesOutPath, renderTypes(icons), "utf8"),
  ]);

  console.log(`Generated ${icons.length} icons → public/icons/sprite.svg + src/icon/icon-names.ts`);
}

// Only build when run directly (`node build-icons.mjs`), not when imported by
// the test, so the self-check can pull in innerOfSvg without doing any I/O.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
